export type MovieData = {
  "id": string,
  "available": string,
  "tmdb": string | null,
  "tvdb": string,
  "imdb_id": string,
  "imdb_episode_id": string | null,
  "title": string,
  "otitle": string,
  "original": string,
  "serie": string,
  "season": string,
  "episode": string,
  "episodetitle": string,
  "oepisodetitle": string,
  "year": string,
  "directors": string,
  "actors": string,
  "companies": string,
  "countries": string,
  "genres": string,
  "channel": string,
  "airtime": string | null,
  "banners": string,
  "posters": string | null,
  "pid": string,
  "provider": string,
  "url": string,
  "seasonurl": string,
  "episodeurl": string,
  "type": string,
  "distribution": string,
  "price": string,
  "publication": string | null,
  "resolution": string,
  "stereoscopic": string,
  "language": string,
  "subtitles": string,
  "audio": string,
  "runtime": string,
  "fsk": string,
  "added": string,
  "modified": string,
  "timestamp": string,
  "expires": string | null,
}
